language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dennistismenko/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true dennistismenko/docker-react npm run test
